include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options


analyzer:
  exclude: [build/**]
  language:
    strict-casts: false
    strict-raw-types: true


linter:
  rules:
    - always_put_required_named_parameters_first
    - avoid_positional_boolean_parameters
    - prefer_final_fields
    - null_check_on_nullable_type_parameter
    - avoid_private_typedef_functions
    - prefer_expression_function_bodies
    - prefer_function_declarations_over_variables
    - prefer_generic_function_type_aliases
    - use_function_type_syntax_for_parameters
    - always_specify_types
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - always_use_package_imports
    - annotate_overrides
    - avoid_annotating_with_dynamic
    - avoid_bool_literals_in_conditional_expressions
    - avoid_catches_without_on_clauses
    - avoid_catching_errors
    - avoid_dynamic_calls
    - avoid_field_initializers_in_const_classes
    - avoid_final_parameters
    - avoid_function_literals_in_foreach_calls
    - avoid_js_rounded_ints
    - avoid_null_checks_in_equality_operators
    - avoid_print
    - avoid_relative_lib_imports
    - avoid_returning_null_for_void
    - avoid_shadowing_type_parameters
    - await_only_futures
    - camel_case_extensions
    - cascade_invocations
    - cast_nullable_to_non_nullable
    - close_sinks
    - comment_references
    - constant_identifier_names
    - control_flow_in_finally
    - curly_braces_in_flow_control_structures
    - directives_ordering
    - eol_at_end_of_file
    - exhaustive_cases
    - file_names
    - flutter_style_todos
    - join_return_with_assignment
    - library_names
    - literal_only_boolean_expressions
    - no_duplicate_case_values
    - prefer_adjacent_string_concatenation
    - prefer_const_constructors
    - type_annotate_public_apis
    - unnecessary_this
    - prefer_is_not_empty
    - prefer_mixin
    - prefer_spread_collections
    - prefer_typing_uninitialized_variables
    - provide_deprecation_message
    - recursive_getters
    - require_trailing_commas
    - sort_child_properties_last
    - type_init_formals
    - unawaited_futures
    - use_key_in_widget_constructors
    - use_late_for_private_fields_and_variables
