name: flutter_social_button
description: Flutter Social Button is a flutter package to create social media login buttons easily to any flutter app.
version: 1.1.5
homepage: https://github.com/alok2811/flutter_social_button

environment:
  sdk: ">=2.15.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
